### ISSUE TITLE
React router vs ssr-server compatibility

### ISSUE THREAD

**Issue by rnarayan** [ssr-server/ssr#7]
This is a question, not an issue.

Currently, my stack is Meteor, React, Redux and React router. I would like my landing page to be server-rendered.

My question is - If I use ssr-server, can I selectively choose which urls get server rendered and which ones client rendered. Also, would I have to get rid of my current client side react-router routes and switch to ssr-server routes for both client and server.

Thanks for help.

**Comment by PEM--** [comment]
Hi @rnarayan. This project is not a router. It's an SSR package. For the router, in our apps we are using react-router-4. Currently in alpha but pretty useable. You can check the demo for some guidelines as well as our FAQ.

I'm closing this issue as we want to keep the repo as clean as possible. Feel free to open some dedicate discussions on Meteor's forum, for instance.

Actually, that would be nice to start a dedicated thread on Meteor's forum so that everyone can share their best practices.
